baseURL = 'https://ajchoi.xyz/'
languageCode = 'en-us'
title = 'Andrew Choi'
[[module.imports]]
path = "github.com/willfaught/paige"

[paige]
color = "#153122" # Bootstrap primary color and theme color for Safari and Windows
math = false # Enable math typesetting
style = "" # CSS included at the end of the stylesheet, before style-last.css

[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 20

[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 30

[[languages.en.menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 40
