baseURL = 'https://ajchoi.xyz/'
languageCode = 'en-us'
title = 'Andrew Choi'
[[module.imports]]
path = "github.com/willfaught/paige"

[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 20

[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 30

[[languages.en.menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 40

[outputs]
home = ["html", "json", "rss"]

[services]
  [services.googleAnalytics]
    ID = 'G-DSMD2C7DF0'
